INSERT INTO public.country (id, names) VALUES (1, '{"ru" : "Австралия", "en" : "Australia"}');
INSERT INTO public.country (id, names) VALUES (2, '{"ru" : "Малайзия", "en" : "Malaysia"}');
INSERT INTO public.country (id, names) VALUES (3, '{"ru" : "Республика Корея", "en" : "Korea"}');
INSERT INTO public.country (id, names) VALUES (4, '{"ru" : "Китай", "en" : "China"}');
INSERT INTO public.country (id, names) VALUES (5, '{"ru" : "Япония", "en" : "Japan"}');
INSERT INTO public.country (id, names) VALUES (6, '{"ru" : "Индия", "en" : "India"}');
INSERT INTO public.country (id, names) VALUES (7, '{"ru" : "Тайвань", "en" : "Taiwan"}');
INSERT INTO public.country (id, names) VALUES (8, '{"ru" : "Гонконг", "en" : "Hong Kong"}');
INSERT INTO public.country (id, names) VALUES (9, '{"ru" : "Таиланд", "en" : "Thailand"}');
INSERT INTO public.country (id, names) VALUES (10, '{"ru" : "Вьетнам", "en" : "Vietnam"}');
INSERT INTO public.country (id, names) VALUES (11, '{"ru" : "Франция", "en" : "France"}');
INSERT INTO public.country (id, names) VALUES (12, '{"ru" : "Италия", "en" : "Italy"}');
INSERT INTO public.country (id, names) VALUES (13, '{"ru" : "Объединенные Арабские Эмираты", "en" : "United Arab Emirates"}');
INSERT INTO public.country (id, names) VALUES (14, '{"ru" : "Швеция", "en" : "Sweden"}');
INSERT INTO public.country (id, names) VALUES (15, '{"ru" : "Казахстан", "en" : "Kazakhstan"}');
INSERT INTO public.country (id, names) VALUES (16, '{"ru" : "Португалия", "en" : "Portugal"}');
INSERT INTO public.country (id, names) VALUES (17, '{"ru" : "Греция", "en" : "Greece"}');
INSERT INTO public.country (id, names) VALUES (18, '{"ru" : "Саудовская Аравия", "en" : "Saudi Arabia"}');
INSERT INTO public.country (id, names) VALUES (19, '{"ru" : "Российская Федерация", "en" : "Russian Federation"}');
INSERT INTO public.country (id, names) VALUES (20, '{"ru" : "Великобритания", "en" : "United Kingdom"}');
INSERT INTO public.country (id, names) VALUES (21, '{"ru" : "Дания", "en" : "Denmark"}');
INSERT INTO public.country (id, names) VALUES (22, '{"ru" : "США", "en" : "United States"}');
INSERT INTO public.country (id, names) VALUES (23, '{"ru" : "Канада", "en" : "Canada"}');
INSERT INTO public.country (id, names) VALUES (24, '{"ru" : "Мексика", "en" : "Mexico"}');
INSERT INTO public.country (id, names) VALUES (25, '{"ru" : "Бермуды", "en" : "Bermuda"}');
INSERT INTO public.country (id, names) VALUES (26, '{"ru" : "Пуэрто Рико", "en" : "Puerto Rico"}');
INSERT INTO public.country (id, names) VALUES (27, '{"ru" : "Виргинские Острова США", "en" : "Virgin Islands, U.S."}');
INSERT INTO public.country (id, names) VALUES (28, '{"ru" : "Германия", "en" : "Germany"}');
INSERT INTO public.country (id, names) VALUES (29, '{"ru" : "Иран", "en" : "Iran"}');
INSERT INTO public.country (id, names) VALUES (30, '{"ru" : "Боливия", "en" : "Bolivia"}');
INSERT INTO public.country (id, names) VALUES (31, '{"ru" : "Монтсеррат", "en" : "Montserrat"}');
INSERT INTO public.country (id, names) VALUES (32, '{"ru" : "Нидерланды", "en" : "Netherlands"}');
INSERT INTO public.country (id, names) VALUES (33, '{"ru" : "Израиль", "en" : "Israel"}');
INSERT INTO public.country (id, names) VALUES (34, '{"ru" : "Испания", "en" : "Spain"}');
INSERT INTO public.country (id, names) VALUES (35, '{"ru" : "Багамские острова", "en" : "Bahamas"}');
INSERT INTO public.country (id, names) VALUES (36, '{"ru" : "Сент-Винсент и Гренадины", "en" : "Saint Vincent and the Grenadines"}');
INSERT INTO public.country (id, names) VALUES (37, '{"ru" : "Чили", "en" : "Chile"}');
INSERT INTO public.country (id, names) VALUES (38, '{"ru" : "Новая Каледония", "en" : "New Caledonia"}');
INSERT INTO public.country (id, names) VALUES (39, '{"ru" : "Аргентина", "en" : "Argentina"}');
INSERT INTO public.country (id, names) VALUES (40, '{"ru" : "Доминика", "en" : "Dominica"}');
INSERT INTO public.country (id, names) VALUES (41, '{"ru" : "Сингапур", "en" : "Singapore"}');
INSERT INTO public.country (id, names) VALUES (42, '{"ru" : "Непал", "en" : "Nepal"}');
INSERT INTO public.country (id, names) VALUES (43, '{"ru" : "Филиппины", "en" : "Philippines"}');
INSERT INTO public.country (id, names) VALUES (44, '{"ru" : "Индонезия", "en" : "Indonesia"}');
INSERT INTO public.country (id, names) VALUES (45, '{"ru" : "Пакистан", "en" : "Pakistan"}');
INSERT INTO public.country (id, names) VALUES (46, '{"ru" : "Токелау", "en" : "Tokelau"}');
INSERT INTO public.country (id, names) VALUES (47, '{"ru" : "Новая Зеландия", "en" : "New Zealand"}');
INSERT INTO public.country (id, names) VALUES (48, '{"ru" : "Камбоджа", "en" : "Cambodia"}');
INSERT INTO public.country (id, names) VALUES (49, '{"ru" : "Макау", "en" : "Macau"}');
INSERT INTO public.country (id, names) VALUES (50, '{"ru" : "Папуа Новая Гвинея", "en" : "Papua New Guinea"}');
INSERT INTO public.country (id, names) VALUES (51, '{"ru" : "Мальдивские острова", "en" : "Maldives"}');
INSERT INTO public.country (id, names) VALUES (52, '{"ru" : "Афганистан", "en" : "Afghanistan"}');
INSERT INTO public.country (id, names) VALUES (53, '{"ru" : "Бангладеш", "en" : "Bangladesh"}');
INSERT INTO public.country (id, names) VALUES (54, '{"ru" : "Ирландия", "en" : "Ireland"}');
INSERT INTO public.country (id, names) VALUES (55, '{"ru" : "Бельгия", "en" : "Belgium"}');
INSERT INTO public.country (id, names) VALUES (56, '{"ru" : "Белиз", "en" : "Belize"}');
INSERT INTO public.country (id, names) VALUES (57, '{"ru" : "Бразилия", "en" : "Brazil"}');
INSERT INTO public.country (id, names) VALUES (58, '{"ru" : "Швейцария", "en" : "Switzerland"}');
INSERT INTO public.country (id, names) VALUES (59, '{"ru" : "Южно-Африканская Республика", "en" : "South Africa"}');
INSERT INTO public.country (id, names) VALUES (60, '{"ru" : "Египет", "en" : "Egypt"}');
INSERT INTO public.country (id, names) VALUES (61, '{"ru" : "Нигерия", "en" : "Nigeria"}');
INSERT INTO public.country (id, names) VALUES (62, '{"ru" : "Танзания", "en" : "Tanzania"}');
INSERT INTO public.country (id, names) VALUES (63, '{"ru" : "Замбия", "en" : "Zambia"}');
INSERT INTO public.country (id, names) VALUES (64, '{"ru" : "Сенегал", "en" : "Senegal"}');
INSERT INTO public.country (id, names) VALUES (65, '{"ru" : "Гана", "en" : "Ghana"}');
INSERT INTO public.country (id, names) VALUES (66, '{"ru" : "Судан", "en" : "Sudan"}');
INSERT INTO public.country (id, names) VALUES (67, '{"ru" : "Камерун", "en" : "Cameroon"}');
INSERT INTO public.country (id, names) VALUES (68, '{"ru" : "Малави", "en" : "Malawi"}');
INSERT INTO public.country (id, names) VALUES (69, '{"ru" : "Ангола", "en" : "Angola"}');
INSERT INTO public.country (id, names) VALUES (70, '{"ru" : "Кения", "en" : "Kenya"}');
INSERT INTO public.country (id, names) VALUES (71, '{"ru" : "Габон", "en" : "Gabon"}');
INSERT INTO public.country (id, names) VALUES (72, '{"ru" : "Мали", "en" : "Mali"}');
INSERT INTO public.country (id, names) VALUES (73, '{"ru" : "Бенин", "en" : "Benin"}');
INSERT INTO public.country (id, names) VALUES (74, '{"ru" : "Мадагаскар", "en" : "Madagascar"}');
INSERT INTO public.country (id, names) VALUES (75, '{"ru" : "Чад", "en" : "Chad"}');
INSERT INTO public.country (id, names) VALUES (76, '{"ru" : "Ботсвана", "en" : "Botswana"}');
INSERT INTO public.country (id, names) VALUES (77, '{"ru" : "Ливия", "en" : "Libya"}');
INSERT INTO public.country (id, names) VALUES (78, '{"ru" : "Кабо-Верде", "en" : "Cape Verde"}');
INSERT INTO public.country (id, names) VALUES (79, '{"ru" : "Руанда", "en" : "Rwanda"}');
INSERT INTO public.country (id, names) VALUES (80, '{"ru" : "Мозамбик", "en" : "Mozambique"}');
INSERT INTO public.country (id, names) VALUES (81, '{"ru" : "Гамбия", "en" : "Gambia"}');
INSERT INTO public.country (id, names) VALUES (82, '{"ru" : "Лесото", "en" : "Lesotho"}');
INSERT INTO public.country (id, names) VALUES (83, '{"ru" : "Маврикий", "en" : "Mauritius"}');
INSERT INTO public.country (id, names) VALUES (84, '{"ru" : "Конго", "en" : "Congo"}');
INSERT INTO public.country (id, names) VALUES (85, '{"ru" : "Уганда", "en" : "Uganda"}');
INSERT INTO public.country (id, names) VALUES (86, '{"ru" : "Буркина Фасо", "en" : "Burkina Faso"}');
INSERT INTO public.country (id, names) VALUES (87, '{"ru" : "Сьерра-Леоне", "en" : "Sierra Leone"}');
INSERT INTO public.country (id, names) VALUES (88, '{"ru" : "Сомали", "en" : "Somalia"}');
INSERT INTO public.country (id, names) VALUES (89, '{"ru" : "Зимбабве", "en" : "Zimbabwe"}');
INSERT INTO public.country (id, names) VALUES (90, '{"ru" : "Демократическая Республика Конго", "en" : "Democratic Republic Of The Congo"}');
INSERT INTO public.country (id, names) VALUES (91, '{"ru" : "Нигер", "en" : "Niger"}');
INSERT INTO public.country (id, names) VALUES (92, '{"ru" : "Центрально-Африканская Республика", "en" : "Central African Republic"}');
INSERT INTO public.country (id, names) VALUES (93, '{"ru" : "Свазиленд", "en" : "Swaziland"}');
INSERT INTO public.country (id, names) VALUES (94, '{"ru" : "Того", "en" : "Togo"}');
INSERT INTO public.country (id, names) VALUES (95, '{"ru" : "Гвинея", "en" : "Guinea"}');
INSERT INTO public.country (id, names) VALUES (96, '{"ru" : "Либерия", "en" : "Liberia"}');
INSERT INTO public.country (id, names) VALUES (97, '{"ru" : "Сейшеллы", "en" : "Seychelles"}');
INSERT INTO public.country (id, names) VALUES (98, '{"ru" : "Марокко", "en" : "Morocco"}');
INSERT INTO public.country (id, names) VALUES (99, '{"ru" : "Алжир", "en" : "Algeria"}');
INSERT INTO public.country (id, names) VALUES (100, '{"ru" : "Мавритания", "en" : "Mauritania"}');
INSERT INTO public.country (id, names) VALUES (101, '{"ru" : "Намибия", "en" : "Namibia"}');
INSERT INTO public.country (id, names) VALUES (102, '{"ru" : "Джибути", "en" : "Djibouti"}');
INSERT INTO public.country (id, names) VALUES (103, '{"ru" : "Коморские острова", "en" : "Comoros"}');
INSERT INTO public.country (id, names) VALUES (104, '{"ru" : "Реюньон", "en" : "Reunion"}');
INSERT INTO public.country (id, names) VALUES (105, '{"ru" : "Экваториальная Гвинея", "en" : "Equatorial Guinea"}');
INSERT INTO public.country (id, names) VALUES (106, '{"ru" : "Тунис", "en" : "Tunisia"}');
INSERT INTO public.country (id, names) VALUES (107, '{"ru" : "Турция", "en" : "Turkey"}');
INSERT INTO public.country (id, names) VALUES (108, '{"ru" : "Польша", "en" : "Poland"}');
INSERT INTO public.country (id, names) VALUES (109, '{"ru" : "Латвия", "en" : "Latvia"}');
INSERT INTO public.country (id, names) VALUES (110, '{"ru" : "Украина", "en" : "Ukraine"}');
INSERT INTO public.country (id, names) VALUES (111, '{"ru" : "Беларусь", "en" : "Belarus"}');
INSERT INTO public.country (id, names) VALUES (112, '{"ru" : "Чехия", "en" : "Czech Republic"}');
INSERT INTO public.country (id, names) VALUES (113, '{"ru" : "Палестина", "en" : "Palestinian Territory"}');
INSERT INTO public.country (id, names) VALUES (114, '{"ru" : "Исландия", "en" : "Iceland"}');
INSERT INTO public.country (id, names) VALUES (115, '{"ru" : "Кипр", "en" : "Cyprus"}');
INSERT INTO public.country (id, names) VALUES (116, '{"ru" : "Венгрия", "en" : "Hungary"}');
INSERT INTO public.country (id, names) VALUES (117, '{"ru" : "Словакия", "en" : "Slovakia"}');
INSERT INTO public.country (id, names) VALUES (118, '{"ru" : "Сербия", "en" : "Serbia"}');
INSERT INTO public.country (id, names) VALUES (119, '{"ru" : "Болгария", "en" : "Bulgaria"}');
INSERT INTO public.country (id, names) VALUES (120, '{"ru" : "Оман", "en" : "Oman"}');
INSERT INTO public.country (id, names) VALUES (121, '{"ru" : "Румыния", "en" : "Romania"}');
INSERT INTO public.country (id, names) VALUES (122, '{"ru" : "Грузия", "en" : "Georgia"}');
INSERT INTO public.country (id, names) VALUES (123, '{"ru" : "Норвегия", "en" : "Norway"}');
INSERT INTO public.country (id, names) VALUES (124, '{"ru" : "Армения", "en" : "Armenia"}');
INSERT INTO public.country (id, names) VALUES (125, '{"ru" : "Австрия", "en" : "Austria"}');
INSERT INTO public.country (id, names) VALUES (126, '{"ru" : "Албания", "en" : "Albania"}');
INSERT INTO public.country (id, names) VALUES (127, '{"ru" : "Словения", "en" : "Slovenia"}');
INSERT INTO public.country (id, names) VALUES (128, '{"ru" : "Панама", "en" : "Panama"}');
INSERT INTO public.country (id, names) VALUES (129, '{"ru" : "Бруней", "en" : "Brunei Darussalam"}');
INSERT INTO public.country (id, names) VALUES (130, '{"ru" : "Шри-Ланка", "en" : "Sri Lanka"}');
INSERT INTO public.country (id, names) VALUES (131, '{"ru" : "Черногория", "en" : "Montenegro"}');
INSERT INTO public.country (id, names) VALUES (132, '{"ru" : "Европейский Союз", "en" : "Europe"}');
INSERT INTO public.country (id, names) VALUES (133, '{"ru" : "Таджикистан", "en" : "Tajikistan"}');
INSERT INTO public.country (id, names) VALUES (134, '{"ru" : "Ирак", "en" : "Iraq"}');
INSERT INTO public.country (id, names) VALUES (135, '{"ru" : "Ливан", "en" : "Lebanon"}');
INSERT INTO public.country (id, names) VALUES (136, '{"ru" : "Молдова", "en" : "Moldova"}');
INSERT INTO public.country (id, names) VALUES (137, '{"ru" : "Финляндия", "en" : "Finland"}');
INSERT INTO public.country (id, names) VALUES (138, '{"ru" : "Эстония", "en" : "Estonia"}');
INSERT INTO public.country (id, names) VALUES (139, '{"ru" : "Босния и Герцеговина", "en" : "Bosnia and Herzegovina"}');
INSERT INTO public.country (id, names) VALUES (140, '{"ru" : "Кувейт", "en" : "Kuwait"}');
INSERT INTO public.country (id, names) VALUES (141, '{"ru" : "Аландские острова", "en" : "Aland Islands"}');
INSERT INTO public.country (id, names) VALUES (142, '{"ru" : "Литва", "en" : "Lithuania"}');
INSERT INTO public.country (id, names) VALUES (143, '{"ru" : "Люксембург", "en" : "Luxembourg"}');
INSERT INTO public.country (id, names) VALUES (144, '{"ru" : "Антигуа и Барбуда", "en" : "Antigua and Barbuda"}');
INSERT INTO public.country (id, names) VALUES (145, '{"ru" : "Македония", "en" : "Macedonia"}');
INSERT INTO public.country (id, names) VALUES (146, '{"ru" : "Сан-Марино", "en" : "San Marino"}');
INSERT INTO public.country (id, names) VALUES (147, '{"ru" : "Мальта", "en" : "Malta"}');
INSERT INTO public.country (id, names) VALUES (148, '{"ru" : "Фолклендские острова", "en" : "Falkland Islands"}');
INSERT INTO public.country (id, names) VALUES (149, '{"ru" : "Бахрейн", "en" : "Bahrain"}');
INSERT INTO public.country (id, names) VALUES (150, '{"ru" : "Узбекистан", "en" : "Uzbekistan"}');
INSERT INTO public.country (id, names) VALUES (151, '{"ru" : "Азербайджан", "en" : "Azerbaijan"}');
INSERT INTO public.country (id, names) VALUES (152, '{"ru" : "Монако", "en" : "Monaco"}');
INSERT INTO public.country (id, names) VALUES (153, '{"ru" : "Гаити", "en" : "Haiti"}');
INSERT INTO public.country (id, names) VALUES (154, '{"ru" : "Гуам", "en" : "Guam"}');
INSERT INTO public.country (id, names) VALUES (155, '{"ru" : "Ямайка", "en" : "Jamaica"}');
INSERT INTO public.country (id, names) VALUES (156, '{"ru" : "Внешние малые острова США", "en" : "United States Minor Outlying Islands"}');
INSERT INTO public.country (id, names) VALUES (157, '{"ru" : "Микронезия", "en" : "Micronesia"}');
INSERT INTO public.country (id, names) VALUES (158, '{"ru" : "Эквадор", "en" : "Ecuador"}');
INSERT INTO public.country (id, names) VALUES (159, '{"ru" : "Перу", "en" : "Peru"}');
INSERT INTO public.country (id, names) VALUES (160, '{"ru" : "Каймановы острова", "en" : "Cayman Islands"}');
INSERT INTO public.country (id, names) VALUES (161, '{"ru" : "Колумбия", "en" : "Colombia"}');
INSERT INTO public.country (id, names) VALUES (162, '{"ru" : "Гондурас", "en" : "Honduras"}');
INSERT INTO public.country (id, names) VALUES (163, '{"ru" : "Антильские острова", "en" : "Netherlands Antilles"}');
INSERT INTO public.country (id, names) VALUES (164, '{"ru" : "Йемен", "en" : "Yemen"}');
INSERT INTO public.country (id, names) VALUES (165, '{"ru" : "Британские Виргинские острова", "en" : "Virgin Islands, British"}');
INSERT INTO public.country (id, names) VALUES (166, '{"ru" : "Сирия", "en" : "Syria"}');
INSERT INTO public.country (id, names) VALUES (167, '{"ru" : "Никарагуа", "en" : "Nicaragua"}');
INSERT INTO public.country (id, names) VALUES (168, '{"ru" : "Доминиканская республика", "en" : "Dominican Republic"}');
INSERT INTO public.country (id, names) VALUES (169, '{"ru" : "Гренада", "en" : "Grenada"}');
INSERT INTO public.country (id, names) VALUES (170, '{"ru" : "Гватемала", "en" : "Guatemala"}');
INSERT INTO public.country (id, names) VALUES (171, '{"ru" : "Коста-Рика", "en" : "Costa Rica"}');
INSERT INTO public.country (id, names) VALUES (172, '{"ru" : "Сальвадор", "en" : "El Salvador"}');
INSERT INTO public.country (id, names) VALUES (173, '{"ru" : "Венесуэла", "en" : "Venezuela"}');
INSERT INTO public.country (id, names) VALUES (174, '{"ru" : "Барбадос", "en" : "Barbados"}');
INSERT INTO public.country (id, names) VALUES (175, '{"ru" : "Тринидад и Тобаго", "en" : "Trinidad and Tobago"}');
INSERT INTO public.country (id, names) VALUES (176, '{"ru" : "Буве", "en" : "Bouvet Island"}');
INSERT INTO public.country (id, names) VALUES (177, '{"ru" : "Маршалловы острова", "en" : "Marshall Islands"}');
INSERT INTO public.country (id, names) VALUES (178, '{"ru" : "Острова Кука", "en" : "Cook Islands"}');
INSERT INTO public.country (id, names) VALUES (179, '{"ru" : "Гибралтар", "en" : "Gibraltar"}');
INSERT INTO public.country (id, names) VALUES (180, '{"ru" : "Парагвай", "en" : "Paraguay"}');
INSERT INTO public.country (id, names) VALUES (181, '{"ru" : "Южный Судан", "en" : "South Sudan"}');
INSERT INTO public.country (id, names) VALUES (182, '{"ru" : "Самоа", "en" : "Samoa"}');
INSERT INTO public.country (id, names) VALUES (183, '{"ru" : "Сент Китс и Невис", "en" : "Saint Kitts and Nevis"}');
INSERT INTO public.country (id, names) VALUES (184, '{"ru" : "Фиджи", "en" : "Fiji"}');
INSERT INTO public.country (id, names) VALUES (185, '{"ru" : "Уругвай", "en" : "Uruguay"}');
INSERT INTO public.country (id, names) VALUES (186, '{"ru" : "Северные Марианские острова", "en" : "Northern Mariana Islands"}');
INSERT INTO public.country (id, names) VALUES (187, '{"ru" : "Палау", "en" : "Palau"}');
INSERT INTO public.country (id, names) VALUES (188, '{"ru" : "Катар", "en" : "Qatar"}');
INSERT INTO public.country (id, names) VALUES (189, '{"ru" : "Иордания", "en" : "Jordan"}');
INSERT INTO public.country (id, names) VALUES (190, '{"ru" : "Американское Самоа", "en" : "American Samoa"}');
INSERT INTO public.country (id, names) VALUES (191, '{"ru" : "Туркс и Кейкос", "en" : "Turks and Caicos Islands"}');
INSERT INTO public.country (id, names) VALUES (192, '{"ru" : "Святая Люсия", "en" : "Saint Lucia"}');
INSERT INTO public.country (id, names) VALUES (193, '{"ru" : "Монголия", "en" : "Mongolia"}');
INSERT INTO public.country (id, names) VALUES (194, '{"ru" : "Ватикан", "en" : "Holy See"}');
INSERT INTO public.country (id, names) VALUES (195, '{"ru" : "Арулько", "en" : "Aruba"}');
INSERT INTO public.country (id, names) VALUES (196, '{"ru" : "Гайана", "en" : "Guyana"}');
INSERT INTO public.country (id, names) VALUES (197, '{"ru" : "Суринам", "en" : "Suriname"}');
INSERT INTO public.country (id, names) VALUES (198, '{"ru" : "Остров Мэн", "en" : "Isle of Man"}');
INSERT INTO public.country (id, names) VALUES (199, '{"ru" : "Вануату", "en" : "Vanuatu"}');
INSERT INTO public.country (id, names) VALUES (200, '{"ru" : "Хорватия", "en" : "Croatia"}');
INSERT INTO public.country (id, names) VALUES (201, '{"ru" : "Ангуилья", "en" : "Anguilla"}');
INSERT INTO public.country (id, names) VALUES (202, '{"ru" : "Сен-Пьер и Микелон", "en" : "Saint Pierre and Miquelon"}');
INSERT INTO public.country (id, names) VALUES (203, '{"ru" : "Гваделупа", "en" : "Guadeloupe"}');
INSERT INTO public.country (id, names) VALUES (204, '{"ru" : "Сен-Мартен", "en" : "Saint Martin"}');
INSERT INTO public.country (id, names) VALUES (205, '{"ru" : "Гернси", "en" : "Guernsey"}');
INSERT INTO public.country (id, names) VALUES (206, '{"ru" : "Бурунди", "en" : "Burundi"}');
INSERT INTO public.country (id, names) VALUES (207, '{"ru" : "Туркменистан", "en" : "Turkmenistan"}');
INSERT INTO public.country (id, names) VALUES (208, '{"ru" : "Кыргызстан", "en" : "Kyrgyzstan"}');
INSERT INTO public.country (id, names) VALUES (209, '{"ru" : "Мьянма", "en" : "Myanmar"}');
INSERT INTO public.country (id, names) VALUES (210, '{"ru" : "Бутан", "en" : "Bhutan"}');
INSERT INTO public.country (id, names) VALUES (211, '{"ru" : "Лихтенштейн", "en" : "Liechtenstein"}');
INSERT INTO public.country (id, names) VALUES (212, '{"ru" : "Фарерские острова", "en" : "Faroe Islands"}');
INSERT INTO public.country (id, names) VALUES (213, '{"ru" : "Эфиопия", "en" : "Ethiopia"}');
INSERT INTO public.country (id, names) VALUES (214, '{"ru" : "Мартиника", "en" : "Martinique"}');
INSERT INTO public.country (id, names) VALUES (215, '{"ru" : "Джерси", "en" : "Jersey"}');
INSERT INTO public.country (id, names) VALUES (216, '{"ru" : "Андорра", "en" : "Andorra"}');
INSERT INTO public.country (id, names) VALUES (217, '{"ru" : "Антарктида", "en" : "Antarctica"}');
INSERT INTO public.country (id, names) VALUES (218, '{"ru" : "Британская территория в Индийском океане", "en" : "British Indian Ocean Territory"}');
INSERT INTO public.country (id, names) VALUES (219, '{"ru" : "Гренландия", "en" : "Greenland"}');
INSERT INTO public.country (id, names) VALUES (220, '{"ru" : "Гвинея-Бисау", "en" : "Guinea-Bissau"}');
INSERT INTO public.country (id, names) VALUES (221, '{"ru" : "Эритрея", "en" : "Eritrea"}');
INSERT INTO public.country (id, names) VALUES (222, '{"ru" : "Уоллис и Футуна", "en" : "Wallis and Futuna"}');
INSERT INTO public.country (id, names) VALUES (223, '{"ru" : "Французская Полинезия", "en" : "French Polynesia"}');
INSERT INTO public.country (id, names) VALUES (224, '{"ru" : "Куба", "en" : "Cuba"}');
INSERT INTO public.country (id, names) VALUES (225, '{"ru" : "Тонга", "en" : "Tonga"}');
INSERT INTO public.country (id, names) VALUES (226, '{"ru" : "Восточный Тимор", "en" : "Timor-Leste"}');
INSERT INTO public.country (id, names) VALUES (227, '{"ru" : "Сан-Томе и Принсипи", "en" : "Sao Tome and Principe"}');
INSERT INTO public.country (id, names) VALUES (228, '{"ru" : "Французская Гвинея", "en" : "French Guiana"}');
INSERT INTO public.country (id, names) VALUES (229, '{"ru" : "Соломоновы острова", "en" : "Solomon Islands"}');
INSERT INTO public.country (id, names) VALUES (230, '{"ru" : "Тувалу", "en" : "Tuvalu"}');
INSERT INTO public.country (id, names) VALUES (231, '{"ru" : "Кирибати", "en" : "Kiribati"}');
INSERT INTO public.country (id, names) VALUES (232, '{"ru" : "Ниуэ", "en" : "Niue"}');
INSERT INTO public.country (id, names) VALUES (233, '{"ru" : "Норфолк", "en" : "Norfolk Island"}');
INSERT INTO public.country (id, names) VALUES (234, '{"ru" : "Науру", "en" : "Nauru"}');
INSERT INTO public.country (id, names) VALUES (235, '{"ru" : "Майотта", "en" : "Mayotte"}');
INSERT INTO public.country (id, names) VALUES (236, '{"ru" : "Питкэрн", "en" : "Pitcairn Islands"}');
INSERT INTO public.country (id, names) VALUES (237, '{"ru" : "Кот-д''Ивуар", "en" : "Cote D''Ivoire"}');
INSERT INTO public.country (id, names) VALUES (238, '{"ru" : "Лаос", "en" : "Lao"}');
INSERT INTO public.country (id, names) VALUES (239, '{"ru" : "Корейская Народно-Демократическая Республика", "en" : "Democratic People''s Republic of Korea"}');
INSERT INTO public.country (id, names) VALUES (240, '{"ru" : "Свальбард и Ян-Майен", "en" : "Svalbard and Jan Mayen"}');
INSERT INTO public.country (id, names) VALUES (241, '{"ru" : "Остров Святой Елены", "en" : "Saint Helena"}');
INSERT INTO public.country (id, names) VALUES (242, '{"ru" : "Кокосовые острова", "en" : "Cocos (Keeling) Islands"}');
INSERT INTO public.country (id, names) VALUES (243, '{"ru" : "Западная Сахара", "en" : "Western Sahara"}');
